services:
  db_students_ci_cd:
    image: postgres 
    container_name: db_students_ci_cd
    restart: always 
    ports:
      - 5000:5432
    env_file:
      - .env 
    volumes:
      - pg_students_ci_cd:/var/lib/postgresql/data
  node_app:
    container_name: node_app
    build: . 
    ports:
      - 5000:5000
    depends_on:
      - db_students_ci_cd 
    env_file:
      - .env 
    volumes:
      pg_students_ci_cd: