name: checkout for pull request
on: [pull_request]
jobs: 
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout for pull request
        uses: actions/checkout@v3
      - name: uses node
        uses: actions/setup-node@v3
      with:
        node-version: '12.x'
      - run: npm run build --if-present
